import "./globals.css";
import { Roboto } from "next/font/google";

const roboto_thin = Roboto({
  subsets: ["cyrillic"],
  weight: "300",
  variable: "--roboto-thin",
});

const roboto_normal = Roboto({
  subsets: ["cyrillic"],
  weight: "400",
  variable: "--roboto-normal",
});

const roboto_bold = Roboto({
  subsets: ["cyrillic"],
  weight: "500",
  variable: "--roboto-bold",
});

const roboto_exBold = Roboto({
  subsets: ["cyrillic"],
  weight: "900",
  variable: "--roboto-exBold",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto_normal.variable} ${roboto_thin.variable} ${roboto_bold.variable} ${roboto_exBold.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
